packages:
  - "services/thesisTool/frontend"
  - "services/website/frontend"
  - "services/contact/frontend"
  - "pkg/frontend/*"
  - "tests/e2e"
  - "tools/storybookextractor"
  - "pkg/testing/a11ytree"