packages:
  - "services/thesisTool/frontend"
  - "services/website/frontend"
  - "services/contact/frontend"
  - "pkg/frontend/*"
  - "pkg/testing/*"
  - "tests/e2e"
  - "tests/playwright"
  - "tools/storybookextractor"
  - "tools/generatePlayWrightA11yTree/packages/playwright"